### PR TITLE
Add additional labels to metrics

### PR DESCRIPTION
**Pull request by YoSev**
## Checklist

- [x] Tests pass (if any)
- [x] Code has been linted/formated
- [x] Documentation updated (where applicable)

## Description
Add additional fields to metrics to allow fine graded separation in grafana
- request_protocol
- request_path
- request_host
- request_port (if exists)
- request_query (if exists)

### CODE REVIEW

**Comment by Bak3y** [comment]
@john-dev heads up you've got a problem the linter's complaining about

**Comment by YoSev** [comment]
To be fair, that error is in you main branch ever since and is raised in every single pull_request you got.

**Comment by YoSev** [comment]
i would advice to fix this in main and rebase the pull_requests to avoid merge conflicts

**Comment by benc-uk** [comment]
Could we remove the overlapping changes in this PR so it just adds the labels, it seems to overlap with the merged PR #15

**Pull request closed without merging**
